name: Deploy Functions on Push
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: functions/package-lock.json
      - run: npm ci
        working-directory: functions
      - uses: w9jds/setup-firebase@v2
        with:
          gcp_sa_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZOLOTAYA_KLETKA_DEFAULT }}
      - run: firebase deploy --only functions --project zolotaya-kletka-default
